name: Android CI

on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/android.yml'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
      - '**/CMakeLists.txt'
jobs:
  build:

    runs-on: ubuntu-22.04
    env: 
      SDK_VERSION: 1.4.309
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: actions/checkout@v4

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          vcpkg_installed
        key: ${{ runner.os }}-primes

    - name: Compile vcpkg dependencies
      run: ./vcpkg.sh android
      
    - name: Save Primes
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: |
          vcpkg_installed
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

    - name: Install Dependencies
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${SDK_VERSION}-jammy.list http://packages.lunarg.com/vulkan/${SDK_VERSION}/lunarg-vulkan-${SDK_VERSION}-jammy.list
        sudo apt-get update
        sudo apt-get install vulkan-sdk
    - name: Compile gkNextRenderer
      run: ./build.sh android