name: Android CI

on: 
  pull_request:
      branches: [main]
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/android.yml'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
      - '**/CMakeLists.txt'
jobs:
  build:

    runs-on: ubuntu-22.04
    env: 
      SDK_VERSION: 1.3.280
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: actions/checkout@v4
    - name: Compile vcpkg dependencies
      run: ./vcpkg_android.sh
    - name: Install Vulkan SDK
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${SDK_VERSION}-jammy.list http://packages.lunarg.com/vulkan/${SDK_VERSION}/lunarg-vulkan-${SDK_VERSION}-jammy.list
        sudo apt-get update
        sudo apt-get install vulkan-sdk
    - name: Compile gkNextRenderer
      run: ./build_android.sh