name: Linux CI

on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/linux.yml'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
      - '**/CMakeLists.txt'
jobs:
  build:
    runs-on: ubuntu-22.04
    env: 
      SDK_VERSION: 1.4.313
    steps:
    - uses: actions/checkout@v4
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl unzip tar libxi-dev libxinerama-dev libxcursor-dev xorg-dev ninja-build
    - name: Install Vulkan SDK
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${SDK_VERSION}-jammy.list http://packages.lunarg.com/vulkan/${SDK_VERSION}/lunarg-vulkan-${SDK_VERSION}-jammy.list
        sudo apt-get update
        sudo apt-get install vulkan-sdk

    # - name: Restore cached Primes
    #   id: cache-primes-restore
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: |
    #       build/vcpkg.linux
    #     key: ${{ runner.os }}-primes

    - name: Compile vcpkg dependencies
      run: ./vcpkg.sh linux

    # - name: Save Primes
    #   id: cache-primes-save
    #   uses: actions/cache/save@v4
    #   with:
    #     path: |
    #       build/vcpkg.linux
    #     key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

    - name: Compile gkNextRenderer
      run: ./build.sh linux
