name: MacOS CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/macos.yml'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
      - '**/CMakeLists.txt'
jobs:
  build:

    runs-on: macos-latest
    env: 
      SDK_VERSION: 1.4.313.1
    steps:
    - uses: actions/checkout@v4
    - name: Install macOS dependencies
      run: |
        brew install ninja
    - name: Install Vulkan SDK
      run: |
        brew install molten-vk
        brew install glslang
    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          build/vcpkg.macos
        key: ${{ runner.os }}-primes

    - name: Compile vcpkg dependencies
      run: ./vcpkg_macos.sh

    - name: Save Primes
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: |
          build/vcpkg.macos
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

    - name: Compile gkNextRenderer
      run: |
        slangc -v
        ./build_macos.sh
