name: MacOS CI

on:
  pull_request:
      branches: [main]
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/macos.yml'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
      - '**/CMakeLists.txt'
jobs:
  build:

    runs-on: macos-12
    env: 
      SDK_VERSION: 1.3.280
    steps:
    - uses: actions/checkout@v4
    - name: Install macOS dependencies
      run: |
        brew install ninja
    - name: Install Vulkan SDK
      run: |
        brew install molten-vk
        brew install glslang
    - name: Compile vcpkg dependencies
      run: ./vcpkg_macos.sh
    - name: Compile gkNextRenderer
      run: ./build_macos.sh
