name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  make-release:
    runs-on: ubuntu-22.04
    outputs:
      uploadurl: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
  android-build:
    needs: make-release
    runs-on: ubuntu-22.04
    env: 
      SDK_VERSION: 1.3.280
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: actions/checkout@v4
    - name: Compile vcpkg dependencies
      run: ./vcpkg_android.sh
    - name: Install Vulkan SDK
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${SDK_VERSION}-jammy.list http://packages.lunarg.com/vulkan/${SDK_VERSION}/lunarg-vulkan-${SDK_VERSION}-jammy.list
        sudo apt-get update
        sudo apt-get install vulkan-sdk
    - name: Compile gkNextRenderer
      run: |
        echo "BUILDVER(${{ github.ref_name }})" > src/build.version
        ./build_android.sh
    - name: Create zip file
      run: |
        zip -r gknextrenderer_android_${{ github.ref_name }}.zip ./android/app/build/outputs/apk/debug/app-debug.apk ./deploy_android.bat
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.make-release.outputs.uploadurl }}
        asset_path: ./gknextrenderer_android_${{ github.ref_name }}.zip
        asset_name: gknextrenderer_android_${{ github.ref_name }}.zip
        asset_content_type: application/zip
  linux-build:
    needs: make-release
    runs-on: ubuntu-22.04
    env: 
      SDK_VERSION: 1.3.280
    steps:
    - uses: actions/checkout@v4
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl unzip tar libxi-dev libxinerama-dev libxcursor-dev xorg-dev ninja-build
    - name: Install Vulkan SDK
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${SDK_VERSION}-jammy.list http://packages.lunarg.com/vulkan/${SDK_VERSION}/lunarg-vulkan-${SDK_VERSION}-jammy.list
        sudo apt-get update
        sudo apt-get install vulkan-sdk
    - name: Compile vcpkg dependencies
      run: |
        echo "BUILDVER(${{ github.ref_name }})" > src/build.version
        ./vcpkg_linux.sh
    - name: Compile gkNextRenderer
      run: ./build_linux.sh
    - name: Create zip file
      run: |
        cd build/linux
        zip -r gknextrenderer_linux64_${{ github.ref_name }}.zip ./bin ./assets/locale ./assets/fonts ./assets/models ./assets/shaders ./assets/textures
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.make-release.outputs.uploadurl }}
        asset_path: ./build/linux/gknextrenderer_linux64_${{ github.ref_name }}.zip
        asset_name: gknextrenderer_linux64_${{ github.ref_name }}.zip
        asset_content_type: application/zip
  windows-build:
    needs: make-release
    runs-on: windows-2022
    env:
      SDK_VERSION: 1.3.280.0
    steps:
    - uses: actions/checkout@v4
    - name: Install zip
      run: choco install zip
    - name: Download Vulkan SDK
      run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/${env:SDK_VERSION}/windows/vulkan_sdk.exe?Human=true" -OutFile vulkan_sdk.exe -v
    - name: Install Vulkan SDK
      run: .\vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
      shell: cmd
    - name: Compile vcpkg dependencies
      run: |
        set VULKAN_SDK=C:\VulkanSDK\%SDK_VERSION%
        vcpkg_windows.bat
      shell: cmd
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Compile gkNextRenderer
      run: |
        set VULKAN_SDK=C:\VulkanSDK\%SDK_VERSION%
        echo BUILDVER(${{ github.ref_name }}) > src/build.version
        build_windows.bat
      shell: cmd
    - name: Create zip file
      run: |
        cd build/windows
        zip -r gknextrenderer_win64_${{ github.ref_name }}.zip ./bin ./assets/locale ./assets/fonts ./assets/models ./assets/shaders ./assets/textures
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.make-release.outputs.uploadurl }}
        asset_path: ./build/windows/gknextrenderer_win64_${{ github.ref_name }}.zip
        asset_name: gknextrenderer_win64_${{ github.ref_name }}.zip
        asset_content_type: application/zip
