name: Windows CI

on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/windows.yml'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
      - '**/CMakeLists.txt'
jobs:
  build:

    runs-on: windows-2022
    env:
      SDK_VERSION: 1.4.313.1
    steps:
    - uses: actions/checkout@v4
    - name: Download Vulkan SDK
      run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/${env:SDK_VERSION}/windows/vulkan_sdk.exe?Human=true" -OutFile vulkan_sdk.exe -v
    - name: Install Vulkan SDK
      run: .\vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
      shell: cmd

    - name: Restore cached vcpkg
      id: cache-vcpkg-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          .vcpkg
        key: ${{ runner.os }}-desktop-vcpkg

    - name: Compile vcpkg dependencies
      run: |
        set VULKAN_SDK=C:\VulkanSDK\%SDK_VERSION%
        vcpkg.bat windows
      shell: cmd

    - name: Save vcpkg to cache
      id: cache-vcpkg-save
      uses: actions/cache/save@v4
      with:
        path: |
          .vcpkg
        key: ${{ steps.cache-vcpkg-restore.outputs.cache-primary-key }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Compile gkNextRenderer
      run: |
        set VULKAN_SDK=C:\VulkanSDK\%SDK_VERSION%
        build.bat windows
      shell: cmd
